version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - db:/var/lib/postgresql/data
  web:
     build: .
     platform: linux/amd64
     volumes:
       - .:/code
     environment:
      - SECRET_KEY=test
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_NAME=agenda
     ports:
       - "8000:8000"
     depends_on:
       - db
volumes:
  db:
    driver: local