# Generated by Django 4.1 on 2022-09-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('company', models.CharField(max_length=25)),
                ('created', models.DateField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
